'use client';
import React, { Suspense, memo, useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import * as THREE from 'three';
import { createBoundedWireCurve, Equipment } from '../../lib/Equipment';
import { COMPONENTS } from '../../lib/components';
import { getComponentTerminals } from '../../lib/terminal-layout';
import { terminalPosition, WIRE_RADIUS, type CircuitRoutes } from '../../lib/routing';
import { endpointEquals, hasOperatingAnimation, pathMatches, placementClear, sceneBounds, selectedPartBounds, snapWorkbenchPoint, tracePresentationPaths, type PathFilter, type RenderQuality } from '../../lib/workbench-presentation';
import { BenchStage } from './BenchStage';
import { SceneLighting } from './SceneLighting';
import { GraphicEffects } from './GraphicEffects';
import type { SceneryId } from '../../lib/scene-settings';
import { useCircuitRouting } from './useCircuitRouting';
import CameraNavigation from './CameraNavigation';
import type { CameraMode } from '../../lib/camera-navigation';
import RoutingWorker from '../../lib/routing.worker?worker';
import type { CircuitDocument, ComponentInstance, DeviceState, Endpoint, SimulationResult, Vec3, Wire } from '../../lib/types';
export { terminalPosition } from '../../lib/routing';
export type { CameraMode } from '../../lib/camera-navigation';
export type Tool = 'select'|'place'|'wire'|'inspect'|'meter';
export type InspectionView = 'normal'|'open'|'exploded'|'cutaway';
export interface WorkbenchMetrics { fps:number;drawCalls:number;triangles:number;dpr:number;quality:RenderQuality;idle:boolean }
export interface WorkbenchProps {
  document:CircuitDocument; result?:SimulationResult; tool:Tool; mode:string; selected?:string; selectedWire?:string;
  selectedPart?:string; view:InspectionView; labels:boolean; paths:boolean; wireStart?:Endpoint; probes:(Endpoint|undefined)[];
  cameraCommand:{id:number;action:string}; onSelect:(id:string,part?:string)=>void; onTerminal:(e:Endpoint)=>void;
  /** Notify only an actual change of the hovered terminal, including leaving it. */
  onTerminalHover?:(endpoint:Endpoint|undefined)=>void;
  onWire:(id:string)=>void; onPlace:(position:Vec3)=>void; onMove:(id:string,position:Vec3,stage:'start'|'move'|'end')=>void;
  onFps:(fps:number)=>void; meterReading:string; meterMode:string;
  cameraMode?:CameraMode;cameraSpeed?:number;scenery?:SceneryId;
  pathFilter?:PathFilter;guidanceEndpoints?:Endpoint[];placeType?:string;quality?:RenderQuality;onMetrics?:(metrics:WorkbenchMetrics)=>void;
}
const createRoutingWorker=()=>new RoutingWorker();
const ignoreRaycast:THREE.Mesh['raycast']=()=>{};
const colours:Record<string,string>={L:'#995039',N:'#2687d8',PE:'#a4da45',L1:'#9e5737',L2:'#36383c',L3:'#899097',control:'#936bc4',output:'#c28036','DC+':'#c34550','DC-':'#465866'};

function Label({label,position,selected=false,width=1.5}:{label:string;position:Vec3;selected?:boolean;width?:number}) {
  const texture=useMemo(()=>{const canvas=document.createElement('canvas');canvas.width=768;canvas.height=128;const ctx=canvas.getContext('2d')!;ctx.fillStyle=selected?'#194b46eb':'#23393beb';ctx.beginPath();ctx.roundRect(2,2,764,124,18);ctx.fill();ctx.strokeStyle=selected?'#90e0c7':'#91a7a7';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#f5faf8';ctx.font='34px Segoe UI, Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label.length>46?label.slice(0,43)+'…':label,384,64,730);const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;return map;},[label,selected]);
  useEffect(()=>()=>texture.dispose(),[texture]);return <sprite position={position} scale={[width,width/6,1]} renderOrder={20}><spriteMaterial map={texture} transparent depthTest={false} depthWrite={false}/></sprite>;
}
function WireModel({wire,points,selected,emphasis,dim,pickable,onClick}:{wire:Wire;points:Vec3[];selected:boolean;emphasis:boolean;dim:boolean;pickable:boolean;onClick:()=>void}) {
  const geometry=useMemo(()=>{const curve=createBoundedWireCurve(points),g=new THREE.TubeGeometry(curve,curve.tubularSegments,WIRE_RADIUS,8,false);if(wire.role==='PE'){const uv=g.getAttribute('uv'),values:number[]=[];for(let i=0;i<uv.count;i++){const colour=new THREE.Color(uv.getY(i)>.5?'#dbcb33':'#3e7a37');values.push(colour.r,colour.g,colour.b);}g.setAttribute('color',new THREE.Float32BufferAttribute(values,3));}return g;},[wire.role,points]);
  useEffect(()=>()=>geometry.dispose(),[geometry]);return <mesh geometry={geometry} userData={{wireId:wire.id}} raycast={pickable?THREE.Mesh.prototype.raycast:ignoreRaycast} onClick={pickable?e=>{e.stopPropagation();onClick();}:undefined} castShadow={!dim}><meshStandardMaterial vertexColors={wire.role==='PE'&&!selected&&!dim} color={selected?'#ffe196':dim?'#81928e':wire.role==='PE'?'#ffffff':colours[wire.role]??'#936bc4'} roughness={.52} metalness={.04} transparent={dim} opacity={dim?.22:1} depthWrite={!dim} emissive={selected?'#d9a742':emphasis?colours[wire.role]??'#936bc4':'#000000'} emissiveIntensity={selected?.25:emphasis?.1:0}/></mesh>;
}
const EquipmentItem=memo(function EquipmentItem({component,state,selected,view,labels,lowDetail,onSelect,onTerminal,register,onDown,onMove,onUp}:{component:ComponentInstance;state?:DeviceState;selected:boolean;view:InspectionView;labels:boolean;lowDetail:boolean;onSelect:(id:string,part?:string)=>void;onTerminal:(endpoint:Endpoint)=>void;register:(id:string,node:THREE.Group|null)=>void;onDown:(event:ThreeEvent<PointerEvent>,component:ComponentInstance)=>void;onMove:(event:ThreeEvent<PointerEvent>)=>void;onUp:(event:ThreeEvent<PointerEvent>)=>void}) {
  const [near,setNear]=useState(false),last=useRef(0),group=useRef<THREE.Group>(null);const def=COMPONENTS[component.type];
  const part=useCallback((id:string)=>onSelect(component.id,id),[component.id,onSelect]),terminal=useCallback((id:string)=>onTerminal({component:component.id,terminal:id}),[component.id,onTerminal]),node=useCallback((value:THREE.Group|null)=>{group.current=value;register(component.id,value);},[component.id,register]);
  useFrame(({camera},dt)=>{last.current+=dt;if(last.current>.4){last.current=0;const close=!!group.current&&camera.position.distanceTo(group.current.getWorldPosition(new THREE.Vector3()))<7.5;if(close!==near)setNear(close);}});
  if(!def)return null;return <group ref={node} position={component.position} rotation={[0,component.rotation,0]} onPointerDown={event=>onDown(event,component)} onPointerMove={onMove} onPointerUp={onUp}><Equipment component={component} definition={def} state={state} selected={selected} view={view} showLabels={false} lowDetail={lowDetail} onPart={part} onTerminal={terminal}/>{labels&&(selected||near)&&<Label label={component.label} selected={selected} position={[0,def.size[1]+.23,0]} width={selected?2:1.55}/>}</group>;
},(a,b)=>a.component===b.component&&a.selected===b.selected&&a.view===b.view&&a.labels===b.labels&&a.lowDetail===b.lowDetail&&a.onSelect===b.onSelect&&a.onTerminal===b.onTerminal&&a.register===b.register&&a.onDown===b.onDown&&a.onMove===b.onMove&&a.onUp===b.onUp&&(['energized','closed','tripped','level','direction','details','moving','elapsed','contactLevel','lightOutputPower'] as const).every(key=>a.state?.[key]===b.state?.[key]));
function SelectionOutline({component,part,nodes,view}:{component?:ComponentInstance;part?:string;nodes:Map<string,THREE.Group>;view:InspectionView}) {
  const [bounds,setBounds]=useState<THREE.Box3>();const {invalidate}=useThree();useEffect(()=>{const frame=requestAnimationFrame(()=>{setBounds(component?selectedPartBounds(component,part,nodes.get(component.id)).expandByScalar(.018):undefined);invalidate();});return()=>cancelAnimationFrame(frame);},[component,part,nodes,view,invalidate]);
  const geometry=useMemo(()=>{if(!bounds)return null;const size=bounds.getSize(new THREE.Vector3()),box=new THREE.BoxGeometry(size.x,size.y,size.z),edges=new THREE.EdgesGeometry(box);box.dispose();return edges;},[bounds]);useEffect(()=>()=>geometry?.dispose(),[geometry]);return bounds&&geometry?<lineSegments position={bounds.getCenter(new THREE.Vector3())} geometry={geometry} renderOrder={8}><lineBasicMaterial color="#2d8f78" transparent opacity={.8} depthTest={false}/></lineSegments>:null;
}
function EndpointMarker({document,endpoint,color,onHover,onClick,label}:{document:CircuitDocument;endpoint:Endpoint;color:string;onHover?:(endpoint?:Endpoint)=>void;onClick?:(endpoint:Endpoint)=>void;label?:string}) {
  const component=document.components.find(c=>c.id===endpoint.component),definition=component&&COMPONENTS[component.type];if(!component||!definition)return null;const terminal=getComponentTerminals(component,definition).find(t=>t.id===endpoint.terminal);if(!terminal)return null;
  return <group position={terminalPosition(document,endpoint)} rotation={[0,component.rotation+Math.PI,0]}><mesh onPointerOver={e=>{e.stopPropagation();onHover?.(endpoint);}} onPointerOut={()=>onHover?.(undefined)} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();onClick?.(endpoint);}}><sphereGeometry args={[.09,12,8]}/><meshBasicMaterial color={color} transparent opacity={onClick?.12:0} depthWrite={false}/></mesh><mesh position={[0,0,.032]} renderOrder={10}><torusGeometry args={[.067,.009,6,24]}/><meshBasicMaterial color={color} depthTest={false}/></mesh>{label&&<Label label={label} selected position={[0,.24,.03]} width={Math.max(.7,Math.min(1.6,label.length*.07))}/>}</group>;
}
function PreviewLine({points,color}:{points:Vec3[];color:string}) {
  const object=useMemo(()=>{const geometry=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p))),material=new THREE.LineDashedMaterial({color,dashSize:.075,gapSize:.045,transparent:true,opacity:.85,depthTest:false}),line=new THREE.Line(geometry,material);line.computeLineDistances();line.renderOrder=14;return line;},[points,color]);useEffect(()=>()=>{object.geometry.dispose();object.material.dispose();},[object]);return <primitive object={object}/>;
}
function RenderController({props,dragging}:{props:WorkbenchProps;dragging:boolean}) {
  const {invalidate,gl,setDpr,camera}=useThree(),stats=useRef({time:0,frames:0,renderMs:0,budget:0,dpr:1.5,reported:false,camera:new THREE.Vector3(),quaternion:new THREE.Quaternion()}),latest=useRef(props);useLayoutEffect(()=>{latest.current=props;},[props]);
  const quality=props.quality??'auto',animated=hasOperatingAnimation(props.document,props.result?.deviceStates),stateKey=JSON.stringify(Object.entries(props.result?.deviceStates??{}).map(([id,state])=>[id,state.energized,state.closed,state.tripped,state.level,state.direction,state.moving,state.contactLevel,state.lightOutputPower]));
  const publish=useCallback((fps:number,idle:boolean)=>{const metrics:WorkbenchMetrics={fps,drawCalls:gl.info.render.calls,triangles:gl.info.render.triangles,dpr:gl.getPixelRatio(),quality:latest.current.quality??'auto',idle};latest.current.onMetrics?.(metrics);window.dispatchEvent(new CustomEvent('electrical-lab-metrics',{detail:metrics}));latest.current.onFps(idle?0:fps);},[gl]);
  useEffect(()=>{stats.current.budget=performance.now()+450;invalidate();},[props.document,stateKey,props.view,props.selected,props.selectedPart,props.labels,props.tool,props.wireStart,props.pathFilter,props.guidanceEndpoints,props.meterReading,props.scenery,props.cameraMode,invalidate]);
  useEffect(()=>{const ratio=quality==='economy'?1:quality==='high'?Math.min(2,window.devicePixelRatio||1):Math.min(1.5,window.devicePixelRatio||1);stats.current.dpr=ratio;setDpr(ratio);invalidate();},[quality,setDpr,invalidate]);
  useEffect(()=>{if(animated||dragging)return;const timer=setTimeout(()=>publish(0,true),550);return()=>clearTimeout(timer);},[animated,dragging,stateKey,props.document,props.cameraCommand,publish]);
  useFrame(()=>{const capture=(window as Window&{__electricalGraphicsDiagnostics?:{frames:number[]}}).__electricalGraphicsDiagnostics;if(capture?.frames&&capture.frames.length<6000)capture.frames.push(performance.now());});
  useFrame((_,dt)=>{const now=performance.now(),sample=stats.current,moved=sample.camera.distanceToSquared(camera.position)>1e-9||Math.abs(sample.quaternion.dot(camera.quaternion))<.999999;sample.camera.copy(camera.position);sample.quaternion.copy(camera.quaternion);if(moved)sample.budget=now+160;const busy=animated||dragging||now<sample.budget;sample.frames++;if(dt<.12)sample.renderMs+=dt*1000;if(!sample.time)sample.time=now;if(busy)invalidate();if(!sample.reported){sample.reported=true;publish(0,!busy);}if(now-sample.time>350&&sample.frames>3||!busy){const fps=Math.round(sample.frames*1000/Math.max(1,now-sample.time));publish(busy?fps:0,!busy);if(quality==='auto'&&busy&&sample.frames>20){const average=sample.renderMs/sample.frames,next=average>23?Math.max(.8,sample.dpr-.15):average<15?Math.min(1.5,window.devicePixelRatio||1,sample.dpr+.08):sample.dpr;if(Math.abs(next-sample.dpr)>.03){sample.dpr=next;setDpr(next);}}sample.time=now;sample.frames=0;sample.renderMs=0;}});return null;
}
function Scene(props:WorkbenchProps&{routing:CircuitRoutes;routingPending:boolean}) {
  const {camera,gl,scene,get}=useThree();
  const [dragging,setDragging]=useState(false),[hover,setHover]=useState<Endpoint>(),hoverRef=useRef<Endpoint|undefined>(undefined),[placement,setPlacement]=useState<Vec3>(),[pointer,setPointer]=useState<Vec3>(),drag=useRef<{id:string;offset:THREE.Vector3;position:Vec3}|null>(null),[nodes]=useState(()=>new Map<string,THREE.Group>()),latest=useRef(props);useLayoutEffect(()=>{latest.current=props;},[props]);
  const plane=useMemo(()=>new THREE.Plane(new THREE.Vector3(0,1,0),0),[]),bounds=useMemo(()=>sceneBounds(props.document,props.routing.routes),[props.document,props.routing.routes]),paths=useMemo(()=>tracePresentationPaths(props.document),[props.document]),filter=props.paths===false?'none':props.pathFilter??'all',chosen=props.document.components.find(c=>c.id===props.selected);
  const components=useMemo(()=>props.document.components.map(c=>['multimeter','clamp'].includes(c.type)?{...c,params:{...c.params,reading:props.meterReading}}:['source','source3'].includes(c.type)?{...c,params:{...c.params,studyVoltage:props.document.supply.voltage}}:c),[props.document.components,props.document.supply.voltage,props.meterReading]);
  const register=useCallback((id:string,node:THREE.Group|null)=>{if(node)nodes.set(id,node);else nodes.delete(id);},[nodes]),registerInstrument=useCallback((node:THREE.Group|null)=>{if(node)nodes.set('@meter',node);else nodes.delete('@meter');},[nodes]),onSelect=useCallback((id:string,part?:string)=>latest.current.onSelect(id,part),[]),onTerminal=useCallback((endpoint:Endpoint)=>latest.current.onTerminal(endpoint),[]);
  const terminalHover=useCallback((endpoint?:Endpoint)=>{if(endpointEquals(hoverRef.current,endpoint)||!hoverRef.current&&!endpoint)return;const next=endpoint?{...endpoint}:undefined;hoverRef.current=next;setHover(next);latest.current.onTerminalHover?.(next);},[]);
  useEffect(()=>{const endpoint=hoverRef.current,component=endpoint&&props.document.components.find(item=>item.id===endpoint.component);if(endpoint&&(!component||!COMPONENTS[component.type]?.terminals.some(terminal=>terminal.id===endpoint.terminal)))terminalHover(undefined);},[props.document.components,terminalHover]);
  // Actuator clicks operate controls; only the housing begins a placement drag.
  const down=useCallback((e:ThreeEvent<PointerEvent>,component:ComponentInstance)=>{const current=latest.current;if(current.tool!=='select'||current.mode!=='build'||e.button!==0)return;let hit:THREE.Object3D|null=e.object;while(hit){if(hit.userData.partId==='actuator')return;hit=hit.parent;}e.stopPropagation();const point=new THREE.Vector3();if(!e.ray.intersectPlane(plane,point))return;drag.current={id:component.id,offset:point.sub(new THREE.Vector3(...component.position)),position:component.position};setDragging(true);current.onMove(component.id,component.position,'start');(e.target as unknown as {setPointerCapture:(id:number)=>void}).setPointerCapture?.(e.pointerId);},[plane]);
  const move=useCallback((e:ThreeEvent<PointerEvent>)=>{if(!drag.current)return;e.stopPropagation();const point=new THREE.Vector3();if(e.ray.intersectPlane(plane,point)){point.sub(drag.current.offset);const position=snapWorkbenchPoint(point.toArray() as Vec3);drag.current.position=position;latest.current.onMove(drag.current.id,position,'move');}},[plane]);const up=useCallback((e:ThreeEvent<PointerEvent>)=>{if(!drag.current)return;e.stopPropagation();latest.current.onMove(drag.current.id,drag.current.position,'end');drag.current=null;setDragging(false);(e.target as unknown as {releasePointerCapture:(id:number)=>void}).releasePointerCapture?.(e.pointerId);},[]);
  const endpoints=useMemo(()=>props.document.components.flatMap(c=>getComponentTerminals(c,COMPONENTS[c.type]).map(t=>({component:c.id,terminal:t.id}))),[props.document.components]),preview=useMemo(()=>{if(!props.wireStart)return null;const from=terminalPosition(props.document,props.wireStart),to=hover?terminalPosition(props.document,hover):pointer;if(!to)return null;return [from,[from[0],from[1],from[2]-.3] as Vec3,[to[0],to[1],to[2]-.3] as Vec3,to];},[props.document,props.wireStart,hover,pointer]);useEffect(()=>{const frame=requestAnimationFrame(()=>{terminalHover(undefined);setPlacement(undefined);});return()=>cancelAnimationFrame(frame);},[props.tool,props.document.id,terminalHover]);
  useEffect(()=>{
    // Read-only diagnostics for the installed application's own QA process.
    // Coordinates come from the live scene/camera, not a second renderer.
    if(!('electricalDesktop' in window))return;
    const report=(event:Event)=>{
      const rect=gl.domElement.getBoundingClientRect(),current=latest.current;camera.updateMatrixWorld(true);
      const wirePickingRequested=(event as CustomEvent<{wirePicking?:boolean}>).detail?.wirePicking===true;
      const describe=(component:ComponentInstance)=>{
        const root=nodes.get(component.id),parts:Record<string,number>={},terminals:Record<string,number>={},assets=new Set<string>(),detailLevels=new Set<string>();root?.updateWorldMatrix(true,true);
        root?.traverse(node=>{if(node.userData.assetKey){assets.add(String(node.userData.assetKey));if(node.userData.lod)detailLevels.add(String(node.userData.lod));}if(node.userData.terminalId)terminals[String(node.userData.terminalId)]=(terminals[String(node.userData.terminalId)]??0)+1;if(node instanceof THREE.Mesh){let owner:THREE.Object3D|null=node;while(owner&&!owner.userData.partId)owner=owner.parent;const part=String(owner?.userData.partId??'decorative');parts[part]=(parts[part]??0)+1;}});
        const projected=getComponentTerminals(component,COMPONENTS[component.type]).map(terminal=>{const point=new THREE.Vector3(...terminalPosition(current.document,{component:component.id,terminal:terminal.id})),screen=point.clone().project(camera);return {id:terminal.id,canonical:point.toArray(),screen:{x:rect.left+(screen.x+1)*rect.width/2,y:rect.top+(1-screen.y)*rect.height/2},inView:Math.abs(screen.x)<=1&&Math.abs(screen.y)<=1&&screen.z>=-1&&screen.z<=1,instances:terminals[terminal.id]??0};});
        const partScreens=Object.fromEntries(Object.keys(parts).map(part=>{const center=selectedPartBounds(component,part,root).getCenter(new THREE.Vector3()).project(camera);return [part,{x:rect.left+(center.x+1)*rect.width/2,y:rect.top+(1-center.y)*rect.height/2,inView:Math.abs(center.x)<=1&&Math.abs(center.y)<=1&&center.z>=-1&&center.z<=1}];}));
        const physicalTerminals:{id:string;position:number[]}[]=[];root?.traverse(node=>{if(node.userData.terminalId)physicalTerminals.push({id:String(node.userData.terminalId),position:node.getWorldPosition(new THREE.Vector3()).toArray()});});
        return {id:component.id,type:component.type,assetKeys:[...assets],detailLevels:[...detailLevels],parts,partScreens,terminals:projected,physicalTerminals};
      };
      const components=current.document.components.map(describe),instruments=current.tool==='meter'?[describe({id:'@meter',type:current.meterMode==='current'?'clamp':'multimeter',label:'Virtual instrument',position:[current.document.components[0]?.position[0]??-4,0,3],rotation:0,params:{reading:current.meterReading}})]:[];
      const wireMeshes=new Map<string,THREE.Mesh>();scene.updateMatrixWorld(true);scene.traverse(node=>{if(node instanceof THREE.Mesh&&typeof node.userData.wireId==='string')wireMeshes.set(node.userData.wireId,node);});
      const raycaster=new THREE.Raycaster(),pickable=current.tool!=='wire'&&(current.tool!=='meter'||current.meterMode==='current'),interactiveObjects=get().internal.interaction;
      const hitDescription=(hit:THREE.Intersection|undefined)=>{if(!hit)return undefined;let owner:THREE.Object3D|null=hit.object,partId:string|undefined,wireId:string|undefined;while(owner){if(typeof owner.userData.partId==='string'&&!partId)partId=owner.userData.partId;if(typeof owner.userData.wireId==='string'&&!wireId)wireId=owner.userData.wireId;owner=owner.parent;}return {name:hit.object.name,type:hit.object.type,wireId,partId,distance:hit.distance};};
      const wires=current.document.wires.map(wire=>{
        const mesh=wireMeshes.get(wire.id),positions=mesh?.geometry.getAttribute('position');
        if(!mesh||!positions)return {id:wire.id,pickPoints:[]};
        // Centres of the rendered tube's actual rings, excluding the duplicated seam vertex.
        // Expensive visibility raycasts run only for an explicit native picking QA request.
        const radialSegments=(mesh.geometry as THREE.TubeGeometry).parameters.radialSegments,ringWidth=radialSegments+1,ringCount=Math.floor(positions.count/ringWidth);
        const sampleCount=wirePickingRequested?24:8;
        const pickPoints=Array.from({length:sampleCount},(_,sample)=>{
          const ring=Math.min(ringCount-1,Math.max(0,Math.round((sample+.5)*(ringCount-1)/sampleCount))),point=new THREE.Vector3();
          for(let index=0;index<radialSegments;index++)point.add(new THREE.Vector3().fromBufferAttribute(positions,ring*ringWidth+index));
          point.divideScalar(radialSegments).applyMatrix4(mesh.matrixWorld);const projected=point.clone().project(camera),inView=Math.abs(projected.x)<=1&&Math.abs(projected.y)<=1&&projected.z>=-1&&projected.z<=1;
          let frontmost=false,nearest:ReturnType<typeof hitDescription>,wireHit:ReturnType<typeof hitDescription>;if(wirePickingRequested&&pickable&&inView){raycaster.setFromCamera(new THREE.Vector2(projected.x,projected.y),camera);const first=raycaster.intersectObjects(interactiveObjects,true)[0];nearest=hitDescription(first);wireHit=hitDescription(raycaster.intersectObject(mesh,false)[0]);frontmost=first?.object===mesh;}
          return {x:rect.left+(projected.x+1)*rect.width/2,y:rect.top+(1-projected.y)*rect.height/2,inView,frontmost,...(wirePickingRequested?{nearest,wireHit}: {})};
        });return {id:wire.id,pickPoints};
      });
      const groundPoints=[-3,-1,1,3].map(x=>{const world:[number,number,number]=[x,0,0],screen=new THREE.Vector3(...world).project(camera);return {world,screen:{x:rect.left+(screen.x+1)*rect.width/2,y:rect.top+(1-screen.y)*rect.height/2},inView:Math.abs(screen.x)<=1&&Math.abs(screen.y)<=1&&screen.z>=-1&&screen.z<=1};});
      window.dispatchEvent(new CustomEvent('electrical-lab-scene',{detail:{circuitId:current.document.id,revision:current.document.revision,view:current.view,routingPending:current.routingPending,components,instruments,wires,wirePickingRequested,...(wirePickingRequested?{wirePickingDebug:{tool:current.tool,pickable,interactiveObjects:interactiveObjects.length,wireMeshes:wireMeshes.size}}:{}),groundPoints}}));
    };
    window.addEventListener('electrical-lab-scene-request',report);return()=>window.removeEventListener('electrical-lab-scene-request',report);
  },[camera,gl,nodes,scene,get]);
  return <><SceneLighting bounds={bounds} document={props.document} result={props.result} scenery={props.scenery} quality={props.quality} selected={props.selected}/><BenchStage bounds={bounds} scenery={props.scenery} quality={props.quality} grid={props.mode==='build'||props.tool==='place'} onPointerMove={e=>{if(props.tool==='place')setPlacement(snapWorkbenchPoint(e.point.toArray() as Vec3));if(props.tool==='wire'&&props.wireStart)setPointer([e.point.x,.08,e.point.z]);move(e);}} onPointerOut={()=>setPlacement(undefined)} onClick={e=>{if(props.tool==='place'){e.stopPropagation();props.onPlace(snapWorkbenchPoint(e.point.toArray() as Vec3));}}}/>
    {props.document.wires.map(wire=>{const points=props.routing.routes.get(wire.id),emphasis=pathMatches(paths.get(wire.id),filter);return points?<WireModel key={wire.id} wire={wire} points={points} pickable={props.tool!=='wire'&&(props.tool!=='meter'||props.meterMode==='current')} selected={props.selectedWire===wire.id} emphasis={filter!=='none'&&emphasis} dim={filter!=='all'&&filter!=='none'&&!emphasis&&props.selectedWire!==wire.id} onClick={()=>props.onWire(wire.id)}/>:null;})}
    {components.map(component=>{const selected=component.id===props.selected||!!(component.params.gangGroup&&component.params.gangGroup===chosen?.params.gangGroup);return <EquipmentItem key={component.id} component={component} state={props.result?.deviceStates[component.id]} selected={selected} view={selected?props.view:'normal'} labels={props.labels} lowDetail={props.quality==='economy'&&!selected} onSelect={onSelect} onTerminal={onTerminal} register={register} onDown={down} onMove={move} onUp={up}/>;})}<SelectionOutline component={chosen} part={props.selectedPart} nodes={nodes} view={props.view}/>
    {(props.tool==='wire'||props.tool==='meter')&&endpoints.map(endpoint=><EndpointMarker key={`${endpoint.component}.${endpoint.terminal}`} document={props.document} endpoint={endpoint} color={endpointEquals(hover,endpoint)?'#ffd871':'#8dbeb7'} onHover={terminalHover} onClick={onTerminal} label={endpointEquals(hover,endpoint)?`${endpoint.component} · ${endpoint.terminal}`:undefined}/>)}{(props.tool==='wire'||props.tool==='meter'||props.view!=='normal'||props.selectedPart==='terminals')&&props.guidanceEndpoints?.map(endpoint=><EndpointMarker key={'guide'+endpoint.component+endpoint.terminal} document={props.document} endpoint={endpoint} color="#31c9a0" label={`Next: ${endpoint.terminal}`}/>)}{props.wireStart&&<EndpointMarker document={props.document} endpoint={props.wireStart} color="#ffca58" label={`From ${props.wireStart.terminal}`}/>} {preview&&<PreviewLine points={preview} color={hover?'#e9bc56':'#aaccc5'}/>}
    {placement&&props.tool==='place'&&props.placeType&&COMPONENTS[props.placeType]&&(()=>{const definition=COMPONENTS[props.placeType!],clear=placementClear(props.document,props.placeType!,placement),color=clear?'#5ad0aa':'#e5a05b';return <group position={placement}><mesh position={[0,definition.size[1]/2,0]}><boxGeometry args={definition.size}/><meshBasicMaterial color={color} transparent opacity={.12} depthWrite={false}/></mesh><mesh position={[0,definition.size[1]/2,0]}><boxGeometry args={definition.size}/><meshBasicMaterial color={color} wireframe transparent opacity={.65}/></mesh><Label position={[0,definition.size[1]+.3,0]} label={`${definition.name} · ${clear?'click to place':'equipment overlaps'}`} selected width={2.4}/></group>;})()}
    {props.tool==='meter'&&<group ref={registerInstrument} position={[props.document.components[0]?.position[0]??-4,0,3]}><Equipment component={{id:'@meter',type:props.meterMode==='current'?'clamp':'multimeter',label:'Virtual instrument',position:[0,0,0],rotation:0,params:{reading:props.meterReading}}} definition={COMPONENTS[props.meterMode==='current'?'clamp':'multimeter']} selected={false} view="normal" showLabels={false} onPart={part=>props.onSelect('@meter',part)} onTerminal={()=>{}}/></group>}{props.tool==='meter'&&props.probes.map((endpoint,index)=>endpoint&&<EndpointMarker key={'probe'+index} document={props.document} endpoint={endpoint} color={index===0?'#e64c52':'#172127'} label={`${index===0?'Red':'Black'} probe`}/>)}
    <CameraNavigation document={props.document} routing={props.routing} routingPending={props.routingPending} selected={props.selected} selectedPart={props.selectedPart} cameraCommand={props.cameraCommand} dragging={dragging} nodes={nodes} mode={props.cameraMode} speed={props.cameraSpeed} tool={props.tool}/><RenderController props={props} dragging={dragging}/><GraphicEffects scenery={props.scenery} quality={props.quality}/></>;
}
class CanvasBoundary extends React.Component<{children:React.ReactNode},{error:boolean}> {state={error:false};static getDerivedStateFromError(){return {error:true};}render(){return this.state.error?<div className="canvas-error"><h3>The 3D view could not start</h3><p>Enable hardware acceleration in your browser and reload. Your saved circuit is preserved.</p></div>:this.props.children;}}
export default function Workbench(props:WorkbenchProps) {
  const {routing,pending,error}=useCircuitRouting(props.document,createRoutingWorker);return <><CanvasBoundary><Canvas shadows={props.quality!=='economy'} frameloop="demand" dpr={[1,1.5]} camera={{position:[6,8,12],fov:43,near:.025,far:140}} gl={{antialias:true,powerPreference:'high-performance'}} onCreated={({gl})=>{gl.shadowMap.type=THREE.PCFSoftShadowMap;gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.05;}}><Suspense fallback={null}><Scene {...props} routing={routing} routingPending={pending}/></Suspense></Canvas></CanvasBoundary>
    {(pending||error)&&<div className="routing-status" role="status" style={{position:'absolute',left:12,bottom:42,zIndex:8,maxWidth:'calc(100% - 24px)',padding:'6px 10px',borderRadius:6,background:'#293547f2',color:error?'#f6ddb1':'#dce7e7',fontSize:12,pointerEvents:'none'}}>{error??'Routing wires…'}</div>}
    {!!routing.issues.length&&<details className="routing-notice" role="status" style={{position:'absolute',left:12,right:12,bottom:42,zIndex:8,maxHeight:160,overflowY:'auto',overflowWrap:'anywhere',whiteSpace:'normal',padding:'8px 11px',borderRadius:6,border:'1px solid #ad8a4e',background:'#293547f2',color:'#f6ddb1',fontSize:12,lineHeight:1.45}}><summary style={{cursor:'pointer',fontWeight:600}}>Routing needs attention: {routing.issues.length} {routing.issues.length===1?'wire':'wires'}</summary><p style={{margin:'6px 0'}}>Move equipment or adjust the listed bends to make room. Select a wire below to inspect it.</p><ul style={{margin:0,paddingLeft:18}}>{routing.issues.map((issue,index)=>{const wire=props.document.wires.find(item=>item.id===issue.wire),label=wire?`${wire.from.component}.${wire.from.terminal} → ${wire.to.component}.${wire.to.terminal}`:issue.wire;return <li key={`${issue.wire}-${index}`} style={{marginTop:4}}><button type="button" onClick={()=>props.onWire(issue.wire)} style={{padding:0,border:0,background:'none',color:'#ffe8b5',textDecoration:'underline',cursor:'pointer',whiteSpace:'normal',overflowWrap:'anywhere',textAlign:'left'}}>{label}</button>: {issue.message}</li>;})}</ul></details>}
  </>;
}
