import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import { LESSONS } from '../lib/lessons.ts';
import { COMPONENTS } from '../lib/components.ts';
import { componentBounds, endpointEquals, hasOperatingAnimation, pathMatches, placementClear, selectedPartBounds, snapWorkbenchPoint, tracePresentationPaths } from '../lib/workbench-presentation.ts';
import { terminalPosition } from '../lib/routing.ts';
import type { CircuitDocument } from '../lib/types.ts';

const example=()=>structuredClone(LESSONS.find(l=>l.id===7)!.circuit);
test('path filters retain PE and open switch paths without simulated current',()=>{const doc=example();const switchItem=doc.components.find(c=>c.type==='switch')!;switchItem.params.closed=false;const paths=tracePresentationPaths(doc);for(const wire of doc.wires){if(wire.role==='PE')assert.ok(pathMatches(paths.get(wire.id),'PE'));if(wire.role==='L')assert.ok(pathMatches(paths.get(wire.id),'L'));assert.ok(pathMatches(paths.get(wire.id),'all'));assert.equal(pathMatches(paths.get(wire.id),'none'),false);}});
test('wrong PE/N join is visible in both connected conductor paths regardless of colour',()=>{const doc=example(),source=doc.components.find(c=>c.type==='source')!,load=doc.components.find(c=>c.type==='lamp')!;doc.wires.push({id:'wrong',from:{component:source.id,terminal:'PE'},to:{component:load.id,terminal:'N'},role:'L',resistance:.01,bends:[]});const paths=tracePresentationPaths(doc);assert.ok(pathMatches(paths.get('wrong'),'PE'));assert.ok(pathMatches(paths.get('wrong'),'N'));assert.equal(pathMatches(paths.get('wrong'),'L'),false);});
test('independent disconnected control wiring stays outside neutral/PE paths',()=>{const doc=example();doc.components.push({id:'control-a',type:'thermostat',label:'Control',position:[5,0,0],rotation:0,params:{}},{id:'control-b',type:'relay',label:'Relay',position:[7,0,0],rotation:0,params:{}});doc.wires.push({id:'control',from:{component:'control-a',terminal:'OUT'},to:{component:'control-b',terminal:'A1'},role:'N',resistance:.01,bends:[]});const categories=tracePresentationPaths(doc).get('control');assert.ok(pathMatches(categories,'control'));assert.equal(pathMatches(categories,'N'),false);assert.equal(pathMatches(categories,'PE'),false);});
test('snap and placement previews never mutate circuit or prevent intentional wrong placements',()=>{const doc=example(),before=JSON.stringify(doc);assert.deepEqual(snapWorkbenchPoint([.38,4,-.37]),[.5,0,-.25]);const first=doc.components[0];assert.equal(placementClear(doc,first.type,first.position),false);assert.equal(placementClear(doc,'switch',[30,0,30]),true);assert.equal(JSON.stringify(doc),before);});
test('rotated terminal focus includes canonical world positions and presentation does not change topology',()=>{const doc=example(),component=doc.components.find(c=>c.type==='switch')!;component.rotation=Math.PI/2;const before=JSON.stringify(doc),bounds=selectedPartBounds(component,'terminals');for(const terminal of COMPONENTS.switch.terminals)assert.ok(bounds.containsPoint(new THREE.Vector3(...terminalPosition(doc,{component:component.id,terminal:terminal.id}))));assert.equal(JSON.stringify(doc),before);const physical=componentBounds(component);assert.ok(physical.getSize(new THREE.Vector3()).x>.7);});
test('semantic node focus resolves a selected part instead of the entire body',()=>{const component=example().components.find(c=>c.type==='switch')!,root=new THREE.Group(),part=new THREE.Mesh(new THREE.BoxGeometry(.1,.2,.03));part.name='part:actuator';part.position.set(0,.7,.3);root.add(part);const bounds=selectedPartBounds(component,'actuator',root),size=bounds.getSize(new THREE.Vector3());assert.ok(size.x<.11);assert.ok(size.y<.21);part.geometry.dispose();});
test('only actual running rotating machinery sustains demand frames',()=>{const doc=example();assert.equal(hasOperatingAnimation(doc,Object.fromEntries(doc.components.map(c=>[c.id,{energized:true}]))),false);doc.components.push({id:'fan',type:'fan',label:'Fan',position:[0,0,0],rotation:0,params:{}});assert.equal(hasOperatingAnimation(doc,{fan:{energized:false}}),false);assert.equal(hasOperatingAnimation(doc,{fan:{energized:true}}),true);assert.ok(endpointEquals({component:'a',terminal:'N'},{component:'a',terminal:'N'}));assert.equal(endpointEquals({component:'a',terminal:'N'},{component:'a',terminal:'PE'}),false);});
